# Challenge 1

The heart disease dataset is a classic dataset that contains various health metrics (age, sex, chest pain type, blood pressure, cholesterol, etc.) related to diagnosing heart disease (binary classification: presence or absence of heart disease).

In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load the dataset (change the path if needed)
df = pd.read_csv('../data/heart.csv')

In [2]:
df.head()

,age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,target
0,63,1,3,145,233,1,0,150,0,2.3,0,0,1,1
1,37,1,2,130,250,0,1,187,0,3.5,0,0,2,1
2,41,0,1,130,204,0,0,172,0,1.4,2,0,2,1
3,56,1,1,120,236,0,1,178,0,0.8,2,0,2,1
4,57,0,0,120,354,0,1,163,1,0.6,2,0,2,1

We are going to try to predict the presence of hart disease suing this features, starting with a classical baseline method and trying to improve on that result with a series of ensembled approaches.

In [42]:
X = df.drop(columns="target")
y = df["target"]

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=0)

# Feature scaling (for certain models, e.g., SVM or logistic regression, not always necessary for trees)
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# Baseline model : decision Tree

We'll train a decision tree as our baseline model and evaluate it using accuracy.

In [43]:
#Create and Train a Decision Tree Classifier and print the train and test accuracy

from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.metrics import (accuracy_score, balanced_accuracy_score, precision_score, recall_score,
                             f1_score, confusion_matrix, classification_report, ConfusionMatrixDisplay)

# creating and choosing the right parameters
rows = []
for depth in [None, 3, 5, 10, 20]:
    for  leaf in [1, 5, 10]:
        t = DecisionTreeClassifier(max_depth=depth,
                               min_samples_leaf= leaf, 
                               random_state=None).fit(X_train, y_train)
        y_pred_t = t.predict(X_test)
        rows.append({"max_depth": str(depth), "depth": t.get_depth(), "leaves": t.get_n_leaves(),
                 "train accuracy": t.score(X_train, y_train), "test accuracy": accuracy_score(y_test, y_pred_t),
                 "recall": recall_score(y_test, y_pred_t), "precision": precision_score(y_test, y_pred_t)})
pd.DataFrame(rows).round(3)

   max_depth  depth  leaves  train accuracy  test accuracy  recall  precision
0       None      9      36           1.000          0.789   0.814      0.814
1       None      6      19           0.890          0.776   0.744      0.842
2       None      5      13           0.855          0.763   0.791      0.791
3          3      3       8           0.855          0.763   0.791      0.791
4          3      3       8           0.855          0.763   0.791      0.791
5          3      3       8           0.855          0.763   0.791      0.791
6          5      5      20           0.934          0.776   0.814      0.795
7          5      5      17           0.885          0.789   0.767      0.846
8          5      5      13           0.855          0.763   0.791      0.791
9         10      9      36           1.000          0.816   0.860      0.822
10        10      6      19           0.890          0.776   0.744      0.842
11        10      5      13           0.855          0.763   0.791      0.791
12        20      9      36           1.000          0.803   0.837      0.818
13        20      6      19           0.890          0.789   0.767      0.846
14        20      5      13           0.855          0.763   0.791      0.791

According to these results a max_depth of 5 and min_sample_leaf of 5 would be the best parameters for this model. With these parameters the recall is low, which is good for a cancer dataset ( we don't want false negatice). Furthermore this parameters show one of the best observed test accuracy, highest precision, and a small overfitting gap.

In [44]:
# Train Decision Tree
tree = DecisionTreeClassifier(max_depth= 5,
                              min_samples_leaf= 5,
                              random_state= None)

tree.fit(X_train, y_train)

# Predictions and evaluation
pred_tree = tree.predict(X_test)

# Evaluate performance
base_test_accuracy = accuracy_score(y_test, pred_tree)
base_train_accuracy = tree.score(X_train, y_train)
print(f"Baseline test accuracy: {base_test_accuracy: .3f}, Baseline train accuracy: {base_train_accuracy: .3f}")

Baseline test accuracy:  0.789, Baseline train accuracy:  0.885

In [45]:
# Train Decision Tree with no parameters
tree_none = DecisionTreeClassifier(random_state= None)

tree_none.fit(X_train, y_train)

# Predictions and evaluation
pred_tree_none = tree_none.predict(X_test)

# Evaluate performance
none_test_accuracy = accuracy_score(y_test, pred_tree_none)
none_train_accuracy = tree_none.score(X_train, y_train)
print(f"Test accuracy: {none_test_accuracy: .3f}, train accuracy: {none_train_accuracy: .3f}")

Test accuracy:  0.789, train accuracy:  1.000

We can see that this model is overfitting. This is expected, decision trees, especially deep ones  are notorious agressive at exploiting the data available. But that also makes them highly variant: a small change on the tree/data makes for potentially large changes in performance.

In [ ]:
# Run the same code again a couple of times. 
# You can see that the Train Accuracy is always 100% (overfitting) and the Test Accuracy is all over the place. 
# This is undesirable: our method is not generalizing and has high variance

# Bagging: reducing variance

Bagging improves models because it reduces variance by averaging the predictions of multiple models trained on different subsets of the training data. This averaging effect reduces the sensitivity of the overall model to any one dataset or model, making the final prediction more stable and less prone to overfitting.

- High-variance models, like decision trees, tend to overfit the training data. This means that small changes in the training data can lead to large changes in the model’s predictions. For example, a decision tree trained on one subset of data might look completely different from a decision tree trained on another subset. This leads to high variance, where the model’s performance fluctuates a lot depending on the specific data it was trained on.
- Once all the individual models are trained, Bagging combines their predictions by averaging them (for regression) or using a majority vote (for classification). The key idea here is that the errors in each individual model are somewhat independent because they are trained on different bootstrap samples. Some models will make errors in one direction, while others might make errors in another. When you average these predictions, the errors cancel out, reducing the overall variability (variance) of the final model.

In [46]:
# Create and Train a BaggingClassifier. 
# Use as base estimator a weak decision tree (max_depth=1) and 100 estimators to really over a lot of different data samples
# Print the train and test accuracy

from sklearn.ensemble import BaggingClassifier
# creating decision trees
# creating weak tree
tree_weak = DecisionTreeClassifier(max_depth= 1,
                              random_state= None)
tree_weak.fit(X_train, y_train)

# Train BaggingClassifier
bagging = BaggingClassifier(estimator= tree_weak, n_estimators=100, random_state=42).fit(X_train, y_train)

# Predictions 
y_pred_bagg = bagging.predict(X_test)

# Evaluate performance
bagg_test_accuracy = accuracy_score(y_test, y_pred_bagg)
bagg_train_accuracy = bagging.score(X_train, y_train)
print(f"Test accuracy: {bagg_test_accuracy: .3f}, train accuracy: {bagg_train_accuracy: .3f}")

Test accuracy:  0.829, train accuracy:  0.824

You can probably see a modest improvement in score, but most importantly, the overfitting is mostly gone. This is because averaging over multiple datasets stabilizes the high variance of the base model.

In [ ]:
# Run the same code again a couple of times. 
# You can see that consistently the Train Accuracy is close to the Test Accuracy.

# Boosting: reducing bias

Now we’ll apply AdaBoost with decision trees as weak learners. This will sequentially improve the model by focusing on difficult cases.

Boosting reduces bias by sequentially training a series of weak learners (often simple models like decision trees) where each subsequent model focuses on the mistakes made by the previous models. The key idea behind boosting is to incrementally improve the model by correcting errors, which helps to reduce bias, especially when the initial model is too simple and underfits the data.

- Boosting typically uses weak learners, which are models that perform only slightly better than random guessing. For example, in classification, a weak learner might be a shallow decision tree (a "stump") with just a few levels. Weak learners usually have high bias, meaning they are too simplistic and don't capture the underlying patterns in the data well. As a result, they underfit the data.

- In each iteration, boosting trains a new model that tries to correct the errors made by the earlier models. If an instance was misclassified by the first weak learner, it will receive a higher weight, so the next model pays more attention to it. As the sequence of models progresses, the ensemble collectively focuses more on the difficult-to-predict instances. Over time, the combined models become better at fitting the data, as they successively reduce the bias (systematic error) by adjusting for earlier mistakes.

In [47]:
# Create and Train a AdaBoostClassifier. 
# Use as base estimator a weak decision tree (max_depth=1) and 100 estimators to really target the specific behaviors of this phenomenon
# Print the train and test accuracy

from sklearn.ensemble import AdaBoostClassifier

# Train AdaBoost
ada = AdaBoostClassifier(estimator= tree_weak, n_estimators=100, random_state=None)
ada.fit(X_train, y_train)
# Predictions 
y_pred_ada = ada.predict(X_test)

# Evaluate performance
ada_test_accuracy = accuracy_score(y_test, y_pred_ada)
ada_train_accuracy = ada.score(X_train, y_train)
print(f"Test accuracy: {ada_test_accuracy: .3f}, train accuracy: {ada_train_accuracy: .3f}")

Test accuracy:  0.868, train accuracy:  0.912

You can probably see a good improvement in score, but overfitting rearing it's ugly head a gain (not as much as in the base model). This is because the iterative correction of adaboost really allows the model to focus on the specifics of this problem, at a cost of overexploiting the dataset.

In [ ]:
# Run the same code again a couple of times. 
# You can see that the test Accuracy will mostly be pretty good, even if some times it get's lower or higher scores (high variance, low bias)
# You can see also that consistently the Train Accuracy is higher than the Test Accuracy,indicating some (not extreme) overfitting